[package]
name = "frontend"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
yew = { version = "0.21.0", features = ["csr"] }
shared = { path = "../shared" }
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["File", "FormData"] }
