[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[package.metadata.tch]
cxx_flags = ["/std:c++17"]

[dependencies]
actix-web = "^4"
actix-files = "0.6.2"
actix-cors = "0.6"
actix-multipart = "0.6.0"
futures = "0.3.28"
torch-sys = "0.19.0"
tch = "0.19.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
aws-config = "0.55.3"
aws-sdk-dynamodb = "0.27.0"
uuid = { version = "1.3.3", features = ["v4", "serde"] }
chrono = { version = "0.4.24", features = ["serde"] }
pyo3 = { version = "0.20.3", features = ["abi3", "auto-initialize"] }
pyo3-build-config = "0.20.3"
base64 = "0.21.2"
log = "0.4.17"
env_logger = "0.10.0"
futures-util = "0.3"
image = "0.24"
shared = { path = "../shared" }
