[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[package.metadata.tch]
cxx_flags = ["/std:c++17"]

[dependencies]
actix-web = "^4"
actix-files = "0.6"
torch-sys = "0.19.0"
tch = "0.19.0"
serde = { version = "1.0", features = ["derive"] }
shared = { path = "../shared" }
