[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.3", features = ["v4", "serde", "js"] }
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1.0"
